services:
  - type: web
    name: programacion-lineal
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    branch: main
    region: oregon
    runtime: python
    pythonVersion: 3.11
